# Generated by Django 3.1.2 on 2020-11-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_magnet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsearch',
            name='middle_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='detailsearch',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='detailsearch',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='detailsearch',
            name='possible_emails',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='detailsearch',
            name='valid_emails',
            field=models.TextField(null=True),
        ),
    ]
