# Generated by Django 3.1.2 on 2020-11-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_magnet', '0003_auto_20201104_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsearch',
            name='domain',
            field=models.CharField(help_text="The domain name of the company that you're targetting. *This is a required field.", max_length=40, verbose_name='Domain name'),
        ),
        migrations.AlterField(
            model_name='detailsearch',
            name='first_name',
            field=models.CharField(help_text="The first name of employer at the company that you're targetting. It is recommended to fill in this field", max_length=30, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='detailsearch',
            name='last_name',
            field=models.CharField(help_text="The last name of employer at the company that you're targetting. It is recommended to fill in this field", max_length=30, null=True, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='detailsearch',
            name='middle_name',
            field=models.CharField(help_text="The middle name of employer at the company that you're targetting. You can leave it blank.", max_length=30, null=True, verbose_name='Middle name'),
        ),
        migrations.AlterField(
            model_name='detailsearch',
            name='possible_emails',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='detailsearch',
            name='valid_emails',
            field=models.TextField(null=True),
        ),
    ]
